name: mtg_stats
description: "mtg stats app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  json_annotation: ^4.9.0

  firebase_core_web: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  json_serializable: ^6.11.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 