name: mtg_stats
description: "mtg stats app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
   # Добавлены для работы с HTTP API:
  http: ^1.6.0

  # Для работы с JSON
  json_annotation: ^4.9.0

  stop_watch_timer: ^3.2.2

  # Интерактивные графики (гистограммы)
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  json_serializable: ^6.11.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 